version: '3.9'

services:

  chromedriver:
    image: selenium/standalone-chrome
    privileged: true
    shm_size: 2g
    ports:
      - 4444:4444

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password123
      - ME_CONFIG_MONGODB_SERVER=mongo
    restart: unless-stopped

  python-app:
    build: .
    depends_on:
      - chromedriver
      - mongo
volumes:
    mongodb:
    mongodb_config: